apiVersion: v1
clusters:
- name: "plex-cluster"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXhNVEUxTVRFMU1Gb1hEVE15TURFeE1URTFNVEUxTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUZtCkhrRlNXOHRTVE5WVTMvVWdjT2V6QnAyMXdvek5NS1BnNkJ4aC9XSTRzbU5HR2pSOTE4Y2JEZVZYa3V0N2hUUUUKcjNaYXFPdjZGdkZGanJkU3AvaUtOWFl4bndEYThNYWcwU2pZdkdKNC9DT3RDL0J1enJPMTc4WFZlZ3E0ZlAvZAo3djVxVUhPaDgvM2g4aXdVMlRNeE55MjBxeUFXbWV2NnR6ODdiZGpVRGc1cGF4Y1U4TGVHMGUwM2I2U1hPWktQCnNIVFlDMktoSGxYV1RTM05yR0UwN3MvNHpxanF3aG0rWm54TFZaOWpSQnB5RHU2Ly9jS3hhZHFHWVVvWXcxWlYKZkwya29vbCszeFFCeVNXelpuV2hYUUd2OGNlSkJMVEgyblA5UE1XSXRCYnZBWjl2bWlDcWlGbVRIcUhoMzlXVwpEYklickxGM3pMRTc2UUJKUy9FQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGRytmazVGSHdjc01VcmpJeEFDSzFOZXB6NVJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCSm94OWd2OW9HajZPa2NtclYzWkt1S3JneDZUTmVxUGw4ZWE4SG00TFpxRG94MUtXNwpyditUSTRpVE95ejNram1DNkJoejlhTEhnVW8ya00zYUdEZ000blpSZ01rVFI3VmV4SzErOFI3dHVmNHZLMkRKClVHMFNucDhWc2pEVlRZbGZPVGVQeHExc1hmWGI4UlY2WXZaRnZCdmZUby9WMGo5NWVJaGtzaGRLcG03QUxxMGcKa1ZqL2ZyV2h4cnNta1Qyc1VVdHJUcDZOWkdKbWY2NDhOK0NzRDZrQzlFQnUyeUROejNuZnhrWXdiMG1reXlKawpRZ2J6b3RMSFROQzM2NlA2eGlwaDVnd2hjVUtRakhCdmR5MzMzKy91UWpJYUFQR25NVXNYdDk5bysyNUcza2RBCmN5OGlpa1p3UGlFSWUzdHNUZTl2a3lLOEhKRTU4bUlYUkRoOQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://26f2b9ae-6b95-4002-a715-c0239d29d8c8.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@plex-cluster
  context:
    cluster: "plex-cluster"
    user: plex-cluster-admin
current-context: admin@plex-cluster
kind: Config
preferences: {}
users:
- name: plex-cluster-admin
  user:
    token: fpuQ43RCoyOf3LQ2yq8RYCkxX4uKQxTBbaTJLJF35A8VfqaMnrAK977w

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    k8s.scw.cloud/ingress: traefik2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8000
  - port: 443
    name: https
    targetPort: 8443
  selector:
    app.kubernetes.io/name: traefik
